//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// USER LOADING
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// CLEAR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

//POST LOADING
export const POSTS_LOADING_REQUEST = "POSTS_LOADING_REQUEST";
export const POSTS_LOADING_SUCCESS = "POSTS_LOADING_SUCCESS";
export const POSTS_LOADING_FAILURE = "POSTS_LOADING_FAILURE";

//POST WRITE
export const POSTS_WRITE_REQUEST = "POSTS_WRITE_REQUEST";
export const POSTS_WRITE_SUCCESS = "POSTS_WRITE_SUCCESS";
export const POSTS_WRITE_FAILURE = "POSTS_WRITE_FAILURE";

//POST UPLOAD
export const POSTS_UPLOADING_REQUEST = "POSTS_UPLOADING_REQUEST";
export const POSTS_UPLOADING_SUCCESS = "POSTS_UPLOADING_SUCCESS";
export const POSTS_UPLOADING_FAILURE = "POSTS_UPLOADING_FAILURE";

//POST DETAIL loading
export const POSTS_DETAIL_LOADING_REQUEST = "POSTS_DETAIL_LOADING_REQUEST";
export const POSTS_DETAIL_LOADING_SUCCESS = "POSTS_DETAIL_LOADING_SUCCESS";
export const POSTS_DETAIL_LOADING_FAILURE = "POSTS_DETAIL_LOADING_FAILURE";

//POST DELETE
export const POSTS_DELETE_REQUEST = "POSTS_DELETE_REQUEST";
export const POSTS_DELETE_SUCCESS = "POSTS_DELETE_SUCCESS";
export const POSTS_DELETE_FAILURE = "POSTS_DELETE_FAILURE";

//POST LOADING EDIT
export const POSTS_EDIT_LOADING_REQUEST = "POSTS_EDIT_LOADING_REQUEST";
export const POSTS_EDIT_LOADING_SUCCESS = "POSTS_EDIT_LOADING_SUCCESS";
export const POSTS_EDIT_LOADING_FAILURE = "POSTS_EDIT_LOADING_FAILURE";

//POST UPLOADING EDIT
export const POSTS_EDIT_UPLOADING_REQUEST = "POSTS_EDIT_UPLOADING_REQUEST";
export const POSTS_EDIT_UPLOADING_SUCCESS = "POSTS_EDIT_UPLOADING_SUCCESS";
export const POSTS_EDIT_UPLOADING_FAILURE = "POSTS_EDIT_UPLOADING_FAILURE";

//COMMENT LOADING
export const COMMENT_LOADING_REQUEST = "COMMENT_LOADING_REQUEST";
export const COMMENT_LOADING_SUCCESS = "COMMENT_LOADING_SUCCESS";
export const COMMENT_LOADING_FAILURE = "COMMENT_LOADING_FAILURE";

//COMMENT UPLOADING
export const COMMENT_UPLOADING_REQUEST = "COMMENT_UPLOADING_REQUEST";
export const COMMENT_UPLOADING_SUCCESS = "COMMENT_UPLOADING_SUCCESS";
export const COMMENT_UPLOADING_FAILURE = "COMMENT_UPLOADING_FAILURE";

//CATEGORY_FIND_REQUEST
export const CATEGORY_FIND_REQUEST = "CATEGORY_FIND_REQUEST";
export const CATEGORY_FIND_SUCCESS = "CATEGORY_FIND_SUCCESS";
export const CATEGORY_FIND_FAILURE = "CATEGORY_FIND_FAILURE";

//SEARCH_REQUEST
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

//Password Edit
export const PASSWORD_EDIT_UPLOADING_REQUEST =
  "PASSWORD_EDIT_UPLOADING_REQUEST";
export const PASSWORD_EDIT_UPLOADING_SUCCESS =
  "PASSWORD_EDIT_UPLOADING_SUCCESS";
export const PASSWORD_EDIT_UPLOADING_FAILURE =
  "PASSWORD_EDIT_UPLOADING_FAILURE";
